apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  namespace: data-analytics-api-api-prod
  labels: { app: analytics-api, component: analytics-api, tenant: data }
spec:
  replicas: 2
  selector: { matchLabels: { component: analytics-api } }
  template:
    metadata: { labels: { app: analytics-api, component: analytics-api } }
    spec:
      containers:
        - name: analytics-api
          image: analytics-api:latest
          ports: [{ containerPort: 8080 }]
